### ISSUE TITLE
[Bug] Uneven side paddings in the expanded sections...

### ISSUE THREAD

**Issue by Mathew20kdroid** [RepoDevil/Himitsu#46]
In the expanded sections in the sub categories for the home , anime and Manga section , the side paddings are uneven ...

![Screenshot_20240521-005905~2.png](https://github.com/RepoDevil/Himitsu/assets/71634955/b82039ff-be32-4996-876e-f20949ff179a)

![Screenshot_20240521-005845~2.png](https://github.com/RepoDevil/Himitsu/assets/71634955/76f274ed-0a5b-4695-a376-753e56013e99)

**Comment by AbandonedCart** [comment]
Interesting. It was the opposite for me

**Comment by AbandonedCart** [comment]
¯\_(ツ)_/¯ Probably fixed, but who knows considering the situation.

**Comment by Mathew20kdroid** [comment]
In the latest update, it's fixed for the card layout, but for the grid layout the side padding is still uneven

**Comment by AbandonedCart** [comment]
Sorry, but due to **constant** harassment stemming from Dantotsu's feelings toward this project, this project is shutting down. While the claims being made were misinformed, the hatred by Dantotsu members is being projected at the users and creating a negative environment for everyone involved. It simply isn't worth contributing to the toxic environment Dantotsu has created.
